---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bundles.operator.werf.dev
spec:
  group: operator.werf.dev
  names:
    kind: Bundle
    listKind: BundleList
    plural: bundles
    singular: bundle
    shortNames:
      - bndl
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.registry
          name: Registry
          type: string
        - jsonPath: .spec.repo
          name: Registry
          type: string
        - jsonPath: .spec.version
          name: Target
          type: string
        - jsonPath: .status.deploy.version
          name: Version
          type: string
        - jsonPath: .status.deploy.digest
          name: Last
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - registry
                - repo
              properties:
                registry:
                  type: string
                repo:
                  type: string
                version:
                  type: string
                  default: latest
                auth:
                  type: string
                project_namespace:
                  type: string
                values:
                  type: string
                env:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                ready:
                  type: integer
                  default: 0
                forceUpdate:
                  type: integer
                  default: 0
                target:
                  type: object
                  properties:
                    digest:
                      type: string
                    version:
                      type: string
                deploy:
                  type: object
                  properties:
                    digest:
                      type: string
                    version:
                      type: string
