# Base example of deployment with operator.
# At first, configure access to the container registry on created namespace 'quickstart-application'
# https://werf.io/documentation/v1.2/advanced/ci_cd/run_in_container/use_kubernetes.html#2-configure-access-to-the-container-registry
# After that, apply this manifests to namespace.
---
apiVersion: v1
kind: Secret
metadata:
  name: public-registry
  # namespace: quickstart-application
type: Opaque
data:
  username: Z2l0bGFiK2RlcGxveS10b2tlbi0xNjI4MTgx
  password: c3QydnZQOFp1QnoyUWhzbjVmc0o=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-values
  # namespace: quickstart-application
data:
  ingress.yaml: |
    ingress:
      enabled: true
  limits.yaml: |
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

---
apiVersion: operator.werf.dev/v1
kind: Bundle
metadata:
  name: test-bundle
  # namespace: quickstart-application
spec:
  registry: registry.gitlab.com
  repo: onegreyonewhite/werf-operator-test-bundle
  version: latest
  auth: public-registry

---
apiVersion: operator.werf.dev/v1
kind: Bundle
metadata:
  name: test-bundle-2
  # namespace: quickstart-application
spec:
  registry: registry.gitlab.com
  repo: onegreyonewhite/werf-operator-test-bundle
  version: 0.1.*
  auth: public-registry
  values: test-values
